# frozen_string_literal: true

module Quakes
  module States
    USA = {
      'alabama' => 'alabama',
      'al' => 'alabama',
      'montana' => 'montana',
      'mt' => 'montana',
      'alaska' => 'alaska',
      'ak' => 'alaska',
      'nebraska' => 'nebraska',
      'ne' => 'nebraska',
      'arizona' => 'arizona',
      'az' => 'arizona',
      'nevada' => 'nevada',
      'nv' => 'nevada',
      'arkansas' => 'arkansas',
      'ar' => 'arkansas',
      'california' => 'california',
      'ca' => 'california',
      'colorado' => 'colorado',
      'co' => 'colorado',
      'connecticut' => 'connecticut',
      'ct' => 'connecticut',
      'delaware' => 'delaware',
      'de' => 'delaware',
      'florida' => 'florida',
      'fl' => 'florida',
      'georgia' => 'georgia',
      'ga' => 'georgia',
      'ohio' => 'ohio',
      'oh' => 'ohio',
      'hawaii' => 'hawaii',
      'hi' => 'hawaii',
      'oklahoma' => 'oklahoma',
      'ok' => 'oklahoma',
      'idaho' => 'idaho',
      'id' => 'idaho',
      'oregon' => 'oregon',
      'or' => 'oregon',
      'illinois' => 'illinois',
      'il' => 'illinois',
      'pennsylvania' => 'pennsylvania',
      'pa' => 'pennsylvania',
      'indiana' => 'indiana',
      'in' => 'indiana',
      'iowa' => 'iowa',
      'ia' => 'iowa',
      'kansas' => 'kansas',
      'ks' => 'kansas',
      'kentucky' => 'kentucky',
      'ky' => 'kentucky',
      'tennessee' => 'tennessee',
      'tn' => 'tennessee',
      'louisiana' => 'louisiana',
      'la' => 'louisiana',
      'texas' => 'texas',
      'tx' => 'texas',
      'maine' => 'maine',
      'me' => 'maine',
      'utah' => 'utah',
      'ut' => 'utah',
      'maryland' => 'maryland',
      'md' => 'maryland',
      'vermont' => 'vermont',
      'vt' => 'vermont',
      'massachusetts' => 'massachusetts',
      'ma' => 'massachusetts',
      'virginia' => 'virginia',
      'va' => 'virginia',
      'michigan' => 'michigan',
      'mi' => 'michigan',
      'washington' => 'washington',
      'wa' => 'washington',
      'minnesota' => 'minnesota',
      'mn' => 'minnesota',
      'mississippi' => 'mississippi',
      'ms' => 'mississippi',
      'wisconsin' => 'wisconsin',
      'wi' => 'wisconsin',
      'missouri' => 'missouri',
      'mo' => 'missouri',
      'wyoming' => 'wyoming',
      'wy' => 'wyoming',
      'new mexico' => 'new mexico',
      'nm' => 'new mexico',
      'new york' => 'new york',
      'ny' => 'new york',
      'north carolina' => 'north carolina',
      'nc' => 'north carolina',
      'north dakota' => 'north dakota',
      'nd' => 'north dakota',
      'rhode island' => 'rhode island',
      'ri' => 'rhode island',
      'south carolina' => 'south carolina',
      'sc' => 'south carolina',
      'south dakota' => 'south dakota',
      'sd' => 'south dakota',
      'new hampshire' => 'new hampshire',
      'nh' => 'new hampshire',
      'new jersey' => 'new jersey',
      'nj' => 'new jersey',
      'west virginia' => 'west virginia',
      'wv' => 'west virginia',
      'american samoa' => 'american samoa',
      'as' => 'american samoa',
      'district of columbia' => 'district of columbia',
      'dc' => 'district of columbia',
      'guam' => 'guam',
      'gu' => 'guam',
      'northern mariana islands' => 'northern mariana islands',
      'mp' => 'northern mariana islands',
      'puerto rico' => 'puerto rico',
      'pr' => 'puerto rico',
      'united states virgin islands' => 'united states virgin islands',
      'vi' => 'united states virgin islands'
    }.freeze

    MAX = USA.keys.max_by { |k| k.size }.size

    def self.max
      MAX
    end

    def self.state_if_exists(name)
      USA.fetch(name, false)
    end
  end
end
